wandb_config:
  wandb_on: False
  project: "HiCHAFL_Parallel"
  entity: "yumiri"
  group: "test"
  name: "FedAvg_mp"
---
data_config:
  data_path: "./data/"
  dataset_name: "MNIST" # cifar10
  num_shards: 200
  iid: False
  split: "gaussian"
---
fed_config:
  C: 1
  K: 10
  R: 1000
  B: 32
  E: 3
  lr: 0.01
  target_acc: 0.99
